package dao;

import java.sql.Connection;
import java.sql.SQLException;


import dao.mappers.IMapResultIntoEntity;
import domain.model.Like;

public class LikeRepository extends RepositoryBase<Like>{

    public LikeRepository(Connection connection, IMapResultIntoEntity<Like> mapper) {
        super(connection,mapper);
    }

    protected String tableName(){
        return "like";
    }

    protected String createTableSql() {
        return "CREATE TABLE like("
            + "likeId bigint GENERATED BY DEFAULT AS IDENTITY,"
            + "sendDate DATE,"
            + "likeFrom INT,"
            + "likeTo INT,"
            + ")";}

    protected String insertSql() {
        return "INSERT INTO like(sendDate,likeFrom,likeTo) VALUES(?,?,?)";
    }
    protected String deleteSql() {
        return "DELETE FROM like WHERE likeId = ?";
    }
    protected String updateSql() {
        return "UPDATE like set sendDate=?, likeFrom=?, likeTo=? WHERE likeId=?";
    }
    protected String selectByIdSql() {
        return "SELECT * FROM like WHERE likeId=?";
    }
    protected String selectAllSql() {
        return "SELECT * FROM like";
    }

    protected void setupInsert(Like entity) throws SQLException{
            insert.setString(1, entity.getSendDate().toString());
            insert.setInt(2, entity.getLikeFrom());
            insert.setInt(3, entity.getLikeTo());
    }
    
    protected void setupUpdate(Like entity) throws SQLException{
            update.setString(1, entity.getSendDate().toString());
            update.setInt(2, entity.getLikeFrom());
            update.setInt(3, entity.getLikeTo());
}
}