package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import domain.model.Like;

public class LikeRepository {

    private Connection connection;

    private String createTableSql = "CREATE TABLE like("
            + "likeId bigint GENERATED BY DEFAULT AS IDENTITY,"
            + "sendDate DATE,"
            + "likeFrom INT,"
            + "likeTo INT,"
            + ")";

    private Statement createTable;

    private String insertSql = "INSERT INTO historyLog(sendDate,accountFrom,accountTo) VALUES(?,?,?)";
    private String deleteSql = "DELETE FROM historyLog WHERE id = ?";

    private PreparedStatement insert;
    private PreparedStatement delete;

    public LikeRepository(Connection connection) {
        this.connection = connection;

        try {
            createTable = connection.createStatement();

            boolean tableExists = false;
            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            while(rs.next()){
                if(rs.getString("TABLE_NAME").equalsIgnoreCase("like")){
                    tableExists=true;
                    break;
                }
            }
            if(!tableExists)
                createTable.executeUpdate(createTableSql);



        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void delete(Like li){
        try{
            delete.setInt(1, li.getLikeId());
            delete.executeUpdate();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }

    public void add(Like li){
        try{

            insert.setString(1, li.getSendDate().toString());
            insert.setInt(3, li.getLikeFrom());
            insert.setInt(4, li.getLikeTo());
            insert.executeUpdate();

        }catch(SQLException ex){
            ex.printStackTrace();
        }

    }

}